CLASS lhc_YOP_DDL_C_POSHEADER DEFINITION INHERITING FROM cl_abap_behavior_handler.
  PRIVATE SECTION.

    METHODS test FOR MODIFY
      IMPORTING keys FOR ACTION yop_ddl_c_posheader~test.

ENDCLASS.

CLASS lhc_YOP_DDL_C_POSHEADER IMPLEMENTATION.

  METHOD test.
  ENDMETHOD.

ENDCLASS.